name: Auto Merge

on:
  pull_request:
    types:
      - opened
      - labeled
      - ready_for_review
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: |
      github.actor == 'github-actions'
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Labels and Author
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: json
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const isBot = pr.data.user.login === "github-actions";
            const hasLabel = pr.data.labels.some(label => label.name === "autorelease: pending");
            return { isBot, hasLabel };

      - name: Approve PR
        if: |
          fromJSON(steps.Check_PR_Labels_and_Author.outputs.result).isBot &&
          fromJSON(steps.Check_PR_Labels_and_Author.outputs.result).hasLabel
        uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approved automated PR"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Filtered PR
        if: |
          fromJSON(steps.Check_PR_Labels_and_Author.outputs.result).isBot &&
          fromJSON(steps.Check_PR_Labels_and_Author.outputs.result).hasLabel
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: "squash"
            });
