name: Auto PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge on PR
        if: ${{ steps.release.outputs.pr }}
        run: gh pr merge --squash --auto "${{ steps.release.outputs.pr }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
