name: Auto Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  
jobs:
  AutoRelease:
    runs-on: ubuntu-latest
    outputs:
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          token: ${{ secrets.GH_PAT }}

      - name: Get release PR number
        id: get_pr
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          PR_NUMBER=$(gh pr list --head release-please--branches--main --json number -q '.[0].number')
          echo "pr=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Enable Pull Request Automerge
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: gh pr merge ${{ steps.get_pr.outputs.pr }} --squash --auto

      - name: Tag version then release
        if: steps.get_pr.outputs.pr != ''
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          token: ${{ secrets.GH_PAT }}
