name: Trigger Docker Repo on Release

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger frappe_docker workflow
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          BODY="${{ github.event.release.body }}"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_DISPATCH_PAT }}" \
            https://api.github.com/repos/digikwal/frappe_docker/dispatches \
            -d "$(jq -n --arg version "$VERSION" --arg changelog "$BODY" '{event_type:"fieldmate-release", client_payload:{version:$version, changelog:$changelog}}')"
