name: Trigger Docker PR on Release

on:
  release:
    types: [published]

jobs:
  trigger-docker-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frappe_docker repo
        uses: actions/checkout@v4
        with:
          repository: digikwal/frappe_docker
          token: ${{ secrets.REPO_DISPATCH_PAT }}
          path: frappe_docker

      - name: Configure git
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Fieldmate Release Bot"

      - name: Prepare update
        working-directory: frappe_docker
        run: |
          echo $(date +%s) > .apps_versions/fieldmate.version
          git checkout -b fieldmate-auto-release

      - name: Commit and push changes
        working-directory: frappe_docker
        run: |
          git add .apps_versions/fieldmate.version
          git commit -m "fieldmate: Trigger rebuild after fieldmate release"
          git push origin fieldmate-auto-release --force

      - name: Create PR in frappe_docker
        working-directory: frappe_docker
	run: |
	  gh pr create \
	    --title "fieldmate(release): Trigger rebuild from new fieldmate release" \
	    --body "$(cat <<EOF
Automated PR triggered by new [release](${{ github.event.release.html_url }}) in **fieldmate**.

      Includes:
      - Trigger for rebuild
      - Optional: changelog info or version ref
      EOF
      )" \
	    --base main \
	    --head fieldmate-auto-release
	env:
	  GH_TOKEN: ${{ secrets.REPO_DISPATCH_PAT }}

